import { z } from 'zod';
export const services = ['Строительство дома','Архитектура и проектирование','Внутренняя отделка','Инженерные системы','Благоустройство территории'] as const;
export const materials = ['Газобетон','Кирпич','Керамические блоки','Дерево','Каркас'] as const;
export const packages = [{id:'warm',name:'Тёплый контур',rate:65000,description:'Фундамент, стены, кровля, окна и входная дверь'},{id:'white',name:'Предчистовая',rate:85000,description:'Тёплый контур, инженерия и подготовка под отделку'},{id:'full',name:'Под ключ',rate:110000,description:'Строительство, инженерия и внутренняя отделка'}] as const;
export const calcSchema=z.object({area:z.number().min(40).max(1000),floors:z.number().int().min(1).max(3),material:z.enum(materials),package:z.enum(['warm','white','full']),design:z.boolean(),landscape:z.boolean(),lawn:z.boolean(),lawnArea:z.number().min(0).max(10000),trees:z.number().int().min(0).max(100),terrace:z.boolean(),lighting:z.boolean(),gazebo:z.boolean()});
export type Calculation=z.infer<typeof calcSchema>;
export const defaultCalculation:Calculation={area:180,floors:2,material:'Газобетон',package:'full',design:false,landscape:false,lawn:false,lawnArea:200,trees:0,terrace:false,lighting:false,gazebo:false};
export function estimate(c:Calculation){const base=packages.find(x=>x.id===c.package)!.rate*c.area;const extras=(c.design?c.area*3000:0)+(c.landscape?150000:0)+(c.lawn?c.lawnArea*800:0);return {base,extras,total:base+extras,individual:[c.material!=='Газобетон'?'Корректировка под выбранный материал':null,c.floors===3?'Конструктив трёхэтажного дома':null,c.trees?`Озеленение: ${c.trees} деревьев`:null,c.terrace?'Терраса':null,c.lighting?'Освещение участка':null,c.gazebo?'Беседка':null].filter(Boolean) as string[]}}
export const money=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)+' ₽';
export function calculatorText(c:Calculation){const e=estimate(c);return `${c.area} м² · ${c.floors} эт. · ${c.material} · ${packages.find(p=>p.id===c.package)!.name}\nДизайн: ${c.design?'да':'нет'}; ландшафтный проект: ${c.landscape?'да':'нет'}; газон: ${c.lawn?c.lawnArea+' м²':'нет'}; деревья: ${c.trees}; терраса: ${c.terrace?'да':'нет'}; освещение: ${c.lighting?'да':'нет'}; беседка: ${c.gazebo?'да':'нет'}\nПредварительно от ${money(e.total)}${e.individual.length?' + индивидуальный расчёт: '+e.individual.join(', '):''}`}
